
package com.example.demo.freeInterface;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InvoiceService", targetNamespace = "http://invoice.services.webservice.business.pccw.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InvoiceService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.cn.phone.InvoiceInfoResponse>
     */
    @WebMethod(operationName = "import_Invoices")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "import_Invoices", targetNamespace = "http://invoice.services.webservice.business.pccw.com/", className = "com.example.demo.freeInterface.ImportInvoices")
    @ResponseWrapper(localName = "import_InvoicesResponse", targetNamespace = "http://invoice.services.webservice.business.pccw.com/", className = "com.example.demo.freeInterface.ImportInvoicesResponse")
    public List<InvoiceInfoResponse> importInvoices(
            @WebParam(name = "arg0", targetNamespace = "")
                    List<InvoiceInfo> arg0);

}
