
package com.example.demo.freeInterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "payrollService", targetNamespace = "http://impl.invoice.services.webservice.business.pccw.com/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/\u8d22\u52a1\u63a5\u53e3/invoiceInfoService_\u6d4b\u8bd5.wsdl")
public class PayrollService
    extends Service
{

    private final static URL PAYROLLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PAYROLLSERVICE_EXCEPTION;
    private final static QName PAYROLLSERVICE_QNAME = new QName("http://impl.invoice.services.webservice.business.pccw.com/", "payrollService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Desktop/\u8d22\u52a1\u63a5\u53e3/invoiceInfoService_\u6d4b\u8bd5.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYROLLSERVICE_WSDL_LOCATION = url;
        PAYROLLSERVICE_EXCEPTION = e;
    }

    public PayrollService() {
        super(__getWsdlLocation(), PAYROLLSERVICE_QNAME);
    }

    public PayrollService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYROLLSERVICE_QNAME, features);
    }

    public PayrollService(URL wsdlLocation) {
        super(wsdlLocation, PAYROLLSERVICE_QNAME);
    }

    public PayrollService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYROLLSERVICE_QNAME, features);
    }

    public PayrollService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PayrollService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InvoiceService
     */
    @WebEndpoint(name = "InvoiceServiceImplPort")
    public InvoiceService getInvoiceServiceImplPort() {
        return super.getPort(new QName("http://impl.invoice.services.webservice.business.pccw.com/", "InvoiceServiceImplPort"), InvoiceService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InvoiceService
     */
    @WebEndpoint(name = "InvoiceServiceImplPort")
    public InvoiceService getInvoiceServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.invoice.services.webservice.business.pccw.com/", "InvoiceServiceImplPort"), InvoiceService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYROLLSERVICE_EXCEPTION!= null) {
            throw PAYROLLSERVICE_EXCEPTION;
        }
        return PAYROLLSERVICE_WSDL_LOCATION;
    }

}
