
package com.example.demo.freepx;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "tcsInfoService", targetNamespace = "http://impl.tcsinfo.services.webservice.business.pccw.com/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/\u8d22\u52a1\u63a5\u53e3/tcsInfoService.wsdl")
public class TcsInfoService_Service
    extends Service
{

    private final static URL TCSINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException TCSINFOSERVICE_EXCEPTION;
    private final static QName TCSINFOSERVICE_QNAME = new QName("http://impl.tcsinfo.services.webservice.business.pccw.com/", "tcsInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrator/Desktop/\u8d22\u52a1\u63a5\u53e3/tcsInfoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TCSINFOSERVICE_WSDL_LOCATION = url;
        TCSINFOSERVICE_EXCEPTION = e;
    }

    public TcsInfoService_Service() {
        super(__getWsdlLocation(), TCSINFOSERVICE_QNAME);
    }

    public TcsInfoService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TCSINFOSERVICE_QNAME, features);
    }

    public TcsInfoService_Service(URL wsdlLocation) {
        super(wsdlLocation, TCSINFOSERVICE_QNAME);
    }

    public TcsInfoService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TCSINFOSERVICE_QNAME, features);
    }

    public TcsInfoService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TcsInfoService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TcsInfoService
     */
    @WebEndpoint(name = "TcsInfoServiceImplPort")
    public TcsInfoService getTcsInfoServiceImplPort() {
        return super.getPort(new QName("http://impl.tcsinfo.services.webservice.business.pccw.com/", "TcsInfoServiceImplPort"), TcsInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TcsInfoService
     */
    @WebEndpoint(name = "TcsInfoServiceImplPort")
    public TcsInfoService getTcsInfoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.tcsinfo.services.webservice.business.pccw.com/", "TcsInfoServiceImplPort"), TcsInfoService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TCSINFOSERVICE_EXCEPTION!= null) {
            throw TCSINFOSERVICE_EXCEPTION;
        }
        return TCSINFOSERVICE_WSDL_LOCATION;
    }

}
